# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1280, 720)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.directory = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory.sizePolicy().hasHeightForWidth())
        self.directory.setSizePolicy(sizePolicy)
        self.directory.setMinimumSize(QtCore.QSize(100, 0))
        self.directory.setObjectName("directory")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.directory)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.model_dir = QtWidgets.QGridLayout()
        self.model_dir.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.model_dir.setObjectName("model_dir")
        self.pushButton_model_dir = QtWidgets.QPushButton(self.directory)
        self.pushButton_model_dir.setObjectName("pushButton_model_dir")
        self.model_dir.addWidget(self.pushButton_model_dir, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.directory)
        self.label_3.setObjectName("label_3")
        self.model_dir.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.model_dir.addItem(spacerItem, 2, 0, 1, 1)
        self.lineEdit_model = QtWidgets.QLineEdit(self.directory)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.model_dir.addWidget(self.lineEdit_model, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.model_dir)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.directory)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_input = QtWidgets.QLineEdit(self.directory)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.gridLayout_3.addWidget(self.lineEdit_input, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.pushButton_input_dir = QtWidgets.QPushButton(self.directory)
        self.pushButton_input_dir.setObjectName("pushButton_input_dir")
        self.gridLayout_3.addWidget(self.pushButton_input_dir, 1, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_output_dir = QtWidgets.QPushButton(self.directory)
        self.pushButton_output_dir.setObjectName("pushButton_output_dir")
        self.gridLayout_4.addWidget(self.pushButton_output_dir, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.directory)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_output = QtWidgets.QLineEdit(self.directory)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.gridLayout_4.addWidget(self.lineEdit_output, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.gridLayout_5.addWidget(self.directory, 0, 0, 1, 1)
        self.model = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model.sizePolicy().hasHeightForWidth())
        self.model.setSizePolicy(sizePolicy)
        self.model.setMinimumSize(QtCore.QSize(300, 0))
        self.model.setObjectName("model")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.model)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.model)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_SSL_t = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_SSL_t.setObjectName("pushButton_SSL_t")
        self.verticalLayout_5.addWidget(self.pushButton_SSL_t)
        self.pushButton_SSL_s = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_SSL_s.setObjectName("pushButton_SSL_s")
        self.verticalLayout_5.addWidget(self.pushButton_SSL_s)
        self.gridLayout_6.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.model)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_active_before = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_active_before.setObjectName("pushButton_active_before")
        self.verticalLayout_6.addWidget(self.pushButton_active_before)
        self.pushButton_active_after = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_active_after.setObjectName("pushButton_active_after")
        self.verticalLayout_6.addWidget(self.pushButton_active_after)
        self.gridLayout_6.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_model = QtWidgets.QComboBox(self.model)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_model)
        self.pushButton_start = QtWidgets.QPushButton(self.model)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_2.addWidget(self.pushButton_start)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.model)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_fewshot_aug = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_fewshot_aug.setObjectName("pushButton_fewshot_aug")
        self.verticalLayout_4.addWidget(self.pushButton_fewshot_aug)
        self.pushButton_fewshot_dota = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_fewshot_dota.setObjectName("pushButton_fewshot_dota")
        self.verticalLayout_4.addWidget(self.pushButton_fewshot_dota)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.model)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_mmdet_air_before = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mmdet_air_before.setObjectName("pushButton_mmdet_air_before")
        self.gridLayout_8.addWidget(self.pushButton_mmdet_air_before, 0, 0, 1, 1)
        self.pushButton_mmdet_ship_before = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mmdet_ship_before.setObjectName("pushButton_mmdet_ship_before")
        self.gridLayout_8.addWidget(self.pushButton_mmdet_ship_before, 0, 1, 1, 1)
        self.pushButton_mmdet_ship_after = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mmdet_ship_after.setObjectName("pushButton_mmdet_ship_after")
        self.gridLayout_8.addWidget(self.pushButton_mmdet_ship_after, 2, 1, 1, 1)
        self.pushButton_mmdet_air_after = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mmdet_air_after.setObjectName("pushButton_mmdet_air_after")
        self.gridLayout_8.addWidget(self.pushButton_mmdet_air_after, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.model)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_attr = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_attr.setObjectName("pushButton_attr")
        self.verticalLayout_3.addWidget(self.pushButton_attr)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.model, 1, 0, 1, 1)
        self.image = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setToolTip("")
        self.image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image.setFlat(False)
        self.image.setObjectName("image")
        self.gridLayout = QtWidgets.QGridLayout(self.image)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_up = QtWidgets.QPushButton(self.image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_up.sizePolicy().hasHeightForWidth())
        self.pushButton_up.setSizePolicy(sizePolicy)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout.addWidget(self.pushButton_up, 4, 2, 1, 1)
        self.label_image = QtWidgets.QLabel(self.image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setMinimumSize(QtCore.QSize(640, 0))
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 2, 2, 1, 2)
        self.pushButton_down = QtWidgets.QPushButton(self.image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_down.sizePolicy().hasHeightForWidth())
        self.pushButton_down.setSizePolicy(sizePolicy)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout.addWidget(self.pushButton_down, 4, 3, 1, 1)
        self.label_image_name = QtWidgets.QLabel(self.image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_name.sizePolicy().hasHeightForWidth())
        self.label_image_name.setSizePolicy(sizePolicy)
        self.label_image_name.setText("")
        self.label_image_name.setObjectName("label_image_name")
        self.gridLayout.addWidget(self.label_image_name, 1, 2, 1, 2)
        self.gridLayout_5.addWidget(self.image, 0, 1, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "遥感影像小样本目标检测软件"))
        self.directory.setTitle(_translate("Dialog", "路径"))
        self.pushButton_model_dir.setText(_translate("Dialog", "打开"))
        self.label_3.setText(_translate("Dialog", "模型路径"))
        self.label_2.setText(_translate("Dialog", "测试图像路径"))
        self.pushButton_input_dir.setText(_translate("Dialog", "打开"))
        self.pushButton_output_dir.setText(_translate("Dialog", "打开"))
        self.label.setText(_translate("Dialog", "测试结果路径"))
        self.model.setTitle(_translate("Dialog", "模型"))
        self.groupBox_4.setTitle(_translate("Dialog", "半监督"))
        self.pushButton_SSL_t.setText(_translate("Dialog", "仅小样本"))
        self.pushButton_SSL_s.setText(_translate("Dialog", "半监督学习"))
        self.groupBox_5.setTitle(_translate("Dialog", "主动学习"))
        self.pushButton_active_before.setText(_translate("Dialog", "仅小样本"))
        self.pushButton_active_after.setText(_translate("Dialog", "主动学习"))
        self.comboBox_model.setItemText(0, _translate("Dialog", "半监督T"))
        self.comboBox_model.setItemText(1, _translate("Dialog", "半监督S"))
        self.comboBox_model.setItemText(2, _translate("Dialog", "仅可见光飞机"))
        self.comboBox_model.setItemText(3, _translate("Dialog", "仅可见光舰船"))
        self.comboBox_model.setItemText(4, _translate("Dialog", "特征迁移飞机"))
        self.comboBox_model.setItemText(5, _translate("Dialog", "特征迁移舰船"))
        self.comboBox_model.setItemText(6, _translate("Dialog", "模型迁移仅红外"))
        self.comboBox_model.setItemText(7, _translate("Dialog", "模型迁移"))
        self.comboBox_model.setItemText(8, _translate("Dialog", "主动学习仅小样本"))
        self.comboBox_model.setItemText(9, _translate("Dialog", "主动学习"))
        self.comboBox_model.setItemText(10, _translate("Dialog", "属性学习"))
        self.pushButton_start.setText(_translate("Dialog", "开始"))
        self.groupBox_3.setTitle(_translate("Dialog", "模型迁移"))
        self.pushButton_fewshot_aug.setText(_translate("Dialog", "仅红外"))
        self.pushButton_fewshot_dota.setText(_translate("Dialog", "模型迁移"))
        self.groupBox.setTitle(_translate("Dialog", "特征迁移"))
        self.pushButton_mmdet_air_before.setText(_translate("Dialog", "仅可见光飞机"))
        self.pushButton_mmdet_ship_before.setText(_translate("Dialog", "仅可见光舰船"))
        self.pushButton_mmdet_ship_after.setText(_translate("Dialog", "特征迁移舰船"))
        self.pushButton_mmdet_air_after.setText(_translate("Dialog", "特征迁移飞机"))
        self.groupBox_2.setTitle(_translate("Dialog", "属性学习"))
        self.pushButton_attr.setText(_translate("Dialog", "属性学习"))
        self.image.setTitle(_translate("Dialog", "测试结果显示"))
        self.pushButton_up.setText(_translate("Dialog", "上一幅"))
        self.label_image.setText(_translate("Dialog", "测试结果"))
        self.pushButton_down.setText(_translate("Dialog", "下一幅"))

